### ISSUE TITLE
未来待解决的问题

### ISSUE THREAD

**Issue by fz6m** [bytedance/guide#10]
1. 打包结果会带有一些 polyfill ，这些 polyfill 自带了 TypeCheck 的报错信息，浪费空间，不太友好，后面应该清理掉所有高阶语法，另外是否自己用 rollup 打包控制流程转而放弃黑盒 father 需要考虑。

2. 没有 demo 站点。

3. dumi doc 排版不太好，13 寸小屏不太友好，有一些覆盖和靠边的问题。

4. 12 个方位假如指定了某个方位，靠屏幕边缘显示不全的时候是否应该自动更改方向，或者增加一个是否靠边自动更改方向的选项。

5. 弹窗动画不太好

6. unpkg 在国内太慢，需要 jsdelivr 加持

7. 类名没有自己的前缀，容易冲突，比如 `byted-guide-*` ，后面应该需要增加前缀或者可自定义前缀。

**Comment by windlany** [comment]
赞，后续我们跟进下，也欢迎提pr
