### ISSUE TITLE
组件渲染时，如果 selector 不存在，会导致遮罩无法关闭，流程也无法继续。

### ISSUE THREAD

**Issue by lianghx-319** [bytedance/guide#15]
- 动态渲染的 element 需要引导时容易发生。
- 现在是自己过滤了一遍 selector
- 建议组件内部就过滤，driverjs 就有这种处理的

**Comment by windlany** [comment]
好的，我们fix下，预计这周内发版

**Comment by windlany** [comment]
已发版，版本：1.0.6
