### ISSUE TITLE
Feature Request: 添加返回上一步向导的功能

### ISSUE THREAD

**Issue by Albert-cord** [bytedance/guide#16]
Hello
我想要添加个功能：返回上一步向导
组件入口添加两个prop: isShowPreviousBtn， prevText
https://github.com/Albert-cord/guide/commit/3aaab57fafaaad221a826b895627df67f78f52a3#r54091694
你看下是否合适，合适的话我后面添加下使用用例、文档说明也添加下属性说明，然后提个PR

**Comment by windlany** [comment]
好的  最近比较忙  我这周内看看

**Comment by windlany** [comment]
好的 已merge
