### ISSUE TITLE
不支持调整高亮元素的区域

### ISSUE THREAD

**Issue by Nico19941206** [bytedance/guide#24]
![image](https://user-images.githubusercontent.com/37568394/150750247-9b7b134f-7e3d-4e01-baa0-d7f5170cff4b.png)
我设置了高亮自定义属性targetPos，发现不生效，看了代码，好像是和高亮元素是二选一的，这里文档描述的好像不一样

**Comment by Nico19941206** [comment]
如果真的二选一，我建议自定义样式默认比高亮元素本身的优先级要高，只是建议哈，具体根据自己业务场景来设定

**Comment by windlany** [comment]
是的，二选一，只能有一个。
自定义样式是指什么呢？现在targetPos是自定义宽高的
