### ISSUE TITLE
observer.observe是否可以监听下anchorEl 的size改变

### ISSUE THREAD

**Issue by feibi** [bytedance/guide#7]
场景：dom已加载，但数据未加载完成

**Comment by windlany** [comment]
可以先用受控的方式解决这个问题，等数据加载完成再展示相关step

**Comment by feibi** [comment]
> 可以先用受控的方式解决这个问题，等数据加载完成再展示相关step

就是不想耦合业务..

**Comment by windlany** [comment]
> > 可以先用受控的方式解决这个问题，等数据加载完成再展示相关step
> 
> 就是不想耦合业务..

好的。我们后续优化一下
